const prompts = [
    { category: "Education", text: "Explain [topic] in simple words for a 14-year-old." },
    { category: "Education", text: "Summarize the chapter '[chapter name]' in bullet points." },
    { category: "Education", text: "Create 5 quiz questions for the topic '[topic]'." },
    { category: "Education", text: "Write a short essay on '[topic]' for a school competition." },
    { category: "Education", text: "Create a mind map for '[topic]'." },
    { category: "Education", text: "Make a timetable for studying all my subjects effectively." },
    { category: "Education", text: "Explain the difference between [concept 1] and [concept 2]." },
    { category: "Education", text: "Create a mnemonic to remember [list of items]." },
    { category: "Education", text: "Suggest practical examples to understand '[topic]' better." },
    { category: "Education", text: "Give me 5 tips for writing better essays." },
    { category: "Education", text: "List important formulas for [subject/topic]." },
    { category: "Education", text: "Generate 10 flashcards for learning [topic]." },
    { category: "Education", text: "Make a revision checklist for my [subject] exam." },
    { category: "Education", text: "Write a poem to remember the process of [process name]." },
    { category: "Education", text: "Create a dialogue between two characters explaining [topic]." },
    { category: "Business", text: "Write a catchy Instagram caption for a product launch." },
    { category: "Business", text: "Create a marketing plan for a small online store." },
    { category: "Business", text: "Write a professional email to a potential client." },
    { category: "Business", text: "Suggest 5 ideas for boosting sales in an offline store." },
    { category: "Business", text: "Write a LinkedIn post about a new business achievement." },
    { category: "Business", text: "Create a 30-second ad script for [product/service]." },
    { category: "Business", text: "Suggest business names for a [type of business]." },
    { category: "Business", text: "Write a product description for an e-commerce listing." },
    { category: "Business", text: "Make a SWOT analysis for a startup idea." },
    { category: "Business", text: "Create a cold email template for lead generation." },
    { category: "Business", text: "List 5 trending business ideas for 2025." },
    { category: "Business", text: "Write an elevator pitch for my business idea." },
    { category: "Business", text: "Generate a pricing strategy for a subscription service." },
    { category: "Business", text: "Create a customer feedback survey template." },
    { category: "Business", text: "Suggest blog topics for a business website." },
    { category: "Coding", text: "Explain how recursion works with examples in Python." },
    { category: "Coding", text: "Write a simple HTML/CSS webpage for a portfolio." },
    { category: "Coding", text: "Debug the following code: [paste code here]." },
    { category: "Coding", text: "Write a JavaScript function to reverse a string." },
    { category: "Coding", text: "Suggest coding projects for beginners in Python." },
    { category: "Coding", text: "Write SQL queries to fetch top 10 customers by revenue." },
    { category: "Coding", text: "Create a basic to-do list app using HTML, CSS, JS." },
    { category: "Coding", text: "Explain object-oriented programming with examples." },
    { category: "Coding", text: "Suggest ways to optimize a slow website." },
    { category: "Coding", text: "Write a Python script to scrape data from a website." },
    { category: "Fun & Creativity", text: "Write a short story about a robot making friends." },
    { category: "Fun & Creativity", text: "Suggest fun party games for teenagers." },
    { category: "Fun & Creativity", text: "Write a rap song about [topic]." },
    { category: "Fun & Creativity", text: "Invent a new holiday and describe how people celebrate it." },
    { category: "Fun & Creativity", text: "Write a mystery riddle for kids." },
    { category: "Fun & Creativity", text: "Create a bucket list of 10 fun activities." },
    { category: "Fun & Creativity", text: "Suggest 5 creative hobbies to try in 2025." },
    { category: "Fun & Creativity", text: "Describe a futuristic city in 100 words." },
    { category: "Fun & Creativity", text: "Write a poem about friendship." },
    { category: "Fun & Creativity", text: "Suggest 5 funny social media challenges." }
];
